# @name Register
POST {{host}}/api/v1/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "{{customer_username}}",
  "password": "{{customer_password}}",
  "fullName": "Philipe Gutemberg Amaral Costa",
  "email": "philipega@live.com",
  "phone": "3285574897",
  "walletAddress": "0xc3d5C17877EfBD914a34281a8F6AD0874f826Bbe"
}