# @name LoginCustomer
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{customer_username}}",
  "password": "{{customer_password}}"
}

###

# @name Tickets
GET {{host}}/api/v1/tickets/owned HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}

###

# @name GetImage
GET {{host}}/api/v1/ticketvalidation/image/6abf41e9-7998-497d-ad9f-b1170e190354 HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json