# @name LoginCustomer
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{customer_username}}",
  "password": "{{customer_password}}"
}

###

# @name List
GET {{host}}/api/v1/events HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}

###

# @name Buy
POST {{host}}/api/v1/events/buy HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json
Content-Length: 55

{
  "EventTicketTypeCode": "07c6c97c-df49-4373-8c6d-5797cfd536b9"
}