# @name Register
POST {{host}}/api/v1/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "{{customer_username}}",
  "password": "{{customer_password}}",
  "fullName": "Laís Felipe de Moraes",
  "email": "sialmoraes@gmail.com",
  "phone": "3285574897",
  "walletAddress": "0xAD119C8bbe517A7b7F2d72DBbDA10cE2344B9375"
}

###

# @name RegisterPhilipe
POST {{host}}/api/v1/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "philipe",
  "password": "sial",
  "fullName": "Philipe Gutemberg Amaral Costa",
  "email": "philipega@live.com",
  "phone": "31994793424",
  "walletAddress": "0xc11cd6Cb821fa0f0B14eFfbad549Cf7E9c3F2A84"
}