# @name LoginCustomer
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{customer_username}}",
  "password": "{{customer_password}}"
}

###

# @name Tickets
GET {{host}}/api/v1/tickets/owned HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}

###

# @name GetTicketHash
GET {{host}}/api/v1/ticketvalidation/hash/tickets/f1e4bb0f-d0ca-489d-bb65-bce01ff7b261 HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json