# @name LoginCustomer
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{usernameCustomer}}",
  "password": "{{passwordCustomer}}"
}

###

# @name List
GET {{host}}/api/v1/events HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}

###

# @name Buy
POST {{host}}/api/v1/events/buy HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json
Content-Length: 55

{
  "EventTicketTypeCode": "b3340fc3-c828-44e0-bc5a-1f95ce0ca981"
}

###

# @name Transfer
POST {{host}}/api/v1/events/transfer HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json
Content-Length: 126

{
  "TicketCode": "7d0b1fcf-ee01-4b2a-9bb0-a09365af21e2"
}