# @name LoginCustomer
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{usernameCustomer}}",
  "password": "{{passwordCustomer}}"
}

###

# @name Create
POST {{host}}/api/v1/events HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json

{
  "startDate": "2023-03-24T00:00:00",
  "endDate": "2023-03-26T00:00:00",
  "location": "Autódromo de Interlagos / SP",
  "title": "Lolapalooza 2023",
  "description": "Lolapalooza 2023",
  "ticker": "LOLA23",
  "imageUrl": "https://portalpopline.com.br/wp-content/uploads/2022/08/Lollapalooza-2023-800x800.jpg",
  "ticketTypes": [
    {
      "ticketName": "Lola Pass (All days)",
      "startDate": "2023-03-24T00:00:00",
      "endDate": "2023-03-26T00:00:00",
      "qualification": "Complimentary",
      "priceBrl": 1250.00,
      "totalTickets": 0
    }
  ]
}

###

# @name List
GET {{host}}/api/v1/events HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}

###

# @name Buy
POST {{host}}/api/v1/events/buy HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json
Content-Length: 55

{
  "EventTicketTypeCode": "6c004eb3-a5ca-4ef2-a56b-fdb0743919c5"
}