# @name LoginGatekeeper
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{gatekeeper_username}}",
  "password": "{{gatekeeper_password}}"
}

###

# @name ValidateTicket
POST {{host}}/api/v1/ticketvalidation/ticket/validate HTTP/1.1
Authorization: Bearer {{LoginGatekeeper.response.body.token}}
Content-Type: application/json

{
  "validationHash": "S/y5NH+cMOWdKGv6wgHLIe9B6PitBqc5ZZiSXZSTDkfj95z2XpQnqa4TOWtKddfZlb3j73CV6uY6TviROlF8pOEDDboscUi5tyxWVoxt7gVxURCyydDeM+hXZSsYM0/vLTGVkpw/rVxRrHE4V1xfrMIwGZWGVNgzUBpLIb2o/UwCWYmrHIB/CA9cimikdDe7720mXuunTJA6sKS/C9E1PAjDUWK4br1/wW+ivizref+2+kOh6kgxTa/1sxMnvCkwJu+V8sfbR3JgoaXnrcRrBaeRKjx7qCsuJ78NdPoVVT0syHO/AWaId/EhxcG0nEQSxhCIspsBWQJ+D6WSws+JbQ=="
}