# @name LoginGatekeeper
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{gatekeeper_username}}",
  "password": "{{gatekeeper_password}}"
}

###

# @name ValidateTicket
POST {{host}}/api/v1/ticketvalidation/ticket/validate HTTP/1.1
Authorization: Bearer {{LoginGatekeeper.response.body.token}}
Content-Type: application/json

{
  "validationHash": "Rl3Xm7Gu0ASnbOJtiEMtlFZcHAhHYY55bB5og2QwYQ7eBbm5qiDM5o1zuLterCFukv018daad95sk50pb8dBU13xGwUIJwnIGaebRZOvTetqeLx+Woz4TQitBFCE+Yi81BVjaXs1RHBqkoRy4BnDWl/ORHILu3gYoS3wYiw1fN5HAolZkJPR7qhTDsjD8VM1uB1YHCah/uTmIzzCB6jyReW4VgA63RlAh8Trw1K8BPI6RwQWHBv+adYtU5yDyHIUzMoobgRiTozv4xQ8kp5EOfNdgEohMSZJZDRbxaqSiHuno4IoSA54lLA+dxXqNE7pVu6boC4UevOAfUqrRhBNsA=="
}