# @name LoginCustomer
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{usernameCustomer}}",
  "password": "{{passwordCustomer}}"
}

###

# @name LoginOperational
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 59

{
  "username": "{{usernameOperational}}",
  "password": "{{passwordOperational}}"
}