# @name LoginCustomer
POST {{host}}/api/v1/login HTTP/1.1
Content-Type: application/json
Content-Length: 55

{
  "username": "{{usernameCustomer}}",
  "password": "{{passwordCustomer}}"
}

###

# @name GetImage
GET {{host}}/api/v1/ticketvalidation/image HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json

{
  "TicketId": "b02e9a15-eb78-4823-a496-97340c09d6e9"
}

###

# @name ValidateTicket
POST {{host}}/api/v1/ticketvalidation/ticket HTTP/1.1
Authorization: Bearer {{LoginCustomer.response.body.token}}
Content-Type: application/json

"gOUI4Mg1+TIT+Lml4w1C1RqFpZ3/FoBiL7xdbT8ghbB/Pa0+2GBcikZ6Q8tFjM0sdGyAishtcn7fO+gPHdFaAps8oZXUwRcXqQcPUUYmqHvMERB62dJnXXWnFvSzMmVjiXwUcMpSVb3XSxQvi6DHbPTxpVCTeYMTMwsJ7jfpYZb8XN54z3t6SHOCRAVW+TTrX/hvuezePM+TT/a5Rrr3SSOf+XUwixY0HSS9Ja89Zl49+HNxNitazdw/jCyXlEIEdY98wrBiDNLIk/znTIXoqVqGtOnGaF8EidwyodkPdcpfTfdcZN1ZlNln3E0MSyPOjwYrsoGjt+49h/V6mjCXvg=="